create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(50) not null,
    active boolean not null default true,
    phone varchar(255),
    address varchar(255),
    created_at timestamp not null,
    updated_at timestamp
);

create table if not exists restaurants (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    location varchar(255) not null,
    cuisine_type varchar(255) not null,
    owner_id bigint not null,
    approved boolean not null default false,
    constraint fk_restaurants_owner foreign key (owner_id) references users(id)
);

create table if not exists menu_items (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    price double precision not null,
    available boolean not null default true,
    restaurant_id bigint not null,
    constraint fk_menu_items_restaurant foreign key (restaurant_id) references restaurants(id) on delete cascade
);

create table if not exists carts (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    restaurant_id bigint not null,
    constraint fk_carts_user foreign key (user_id) references users(id),
    constraint fk_carts_restaurant foreign key (restaurant_id) references restaurants(id)
);

create table if not exists cart_items (
    id bigint generated by default as identity primary key,
    menu_item_id bigint not null,
    name varchar(255) not null,
    price double precision not null,
    quantity integer not null,
    cart_id bigint not null,
    constraint fk_cart_items_cart foreign key (cart_id) references carts(id) on delete cascade,
    constraint fk_cart_items_menu_item foreign key (menu_item_id) references menu_items(id)
);

create table if not exists orders (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    restaurant_id bigint not null,
    delivery_agent_id bigint,
    total_amount double precision not null,
    order_status varchar(50) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_orders_user foreign key (user_id) references users(id),
    constraint fk_orders_restaurant foreign key (restaurant_id) references restaurants(id),
    constraint fk_orders_delivery_agent foreign key (delivery_agent_id) references users(id)
);

create table if not exists order_items (
    id bigint generated by default as identity primary key,
    menu_item_id bigint not null,
    name varchar(255) not null,
    price double precision not null,
    quantity integer not null,
    order_id bigint not null,
    constraint fk_order_items_order foreign key (order_id) references orders(id) on delete cascade,
    constraint fk_order_items_menu_item foreign key (menu_item_id) references menu_items(id)
);

create table if not exists payments (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique,
    amount double precision not null,
    status varchar(50) not null,
    transaction_id varchar(255) not null unique,
    created_at timestamp not null,
    constraint fk_payments_order foreign key (order_id) references orders(id)
);

create index if not exists idx_restaurants_owner_id on restaurants(owner_id);
create index if not exists idx_menu_items_restaurant_id on menu_items(restaurant_id);
create index if not exists idx_orders_user_id on orders(user_id);
create index if not exists idx_orders_restaurant_id on orders(restaurant_id);
create index if not exists idx_orders_delivery_agent_id on orders(delivery_agent_id);
create index if not exists idx_payments_order_id on payments(order_id);
