alter table users add column if not exists token_version integer not null default 0;

create table if not exists refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token varchar(255) not null unique,
    expires_at timestamp not null,
    revoked boolean not null default false,
    created_at timestamp not null,
    revoked_at timestamp,
    constraint fk_refresh_tokens_user foreign key (user_id) references users(id)
);

create index if not exists idx_refresh_tokens_user_id on refresh_tokens(user_id);
