

create table if not exists reviews (
                                       id               bigint generated by default as identity primary key,
                                       user_id          bigint        not null,
                                       order_id         bigint        not null,
                                       review_type      varchar(50)   not null,  -- RESTAURANT | MENU_ITEM | DELIVERY_AGENT
    target_id        bigint        not null,
    rating           integer       not null check (rating >= 1 and rating <= 5),
    comment          varchar(1000),
    created_at       timestamp     not null,
    updated_at       timestamp,

    constraint fk_reviews_user  foreign key (user_id)  references users(id),
    constraint fk_reviews_order foreign key (order_id) references orders(id),

    -- One review per user per (type + target) per order
    constraint uq_review_user_type_target_order
    unique (user_id, review_type, target_id, order_id)
    );

create index if not exists idx_reviews_type_target  on reviews(review_type, target_id);
create index if not exists idx_reviews_user_id       on reviews(user_id);
create index if not exists idx_reviews_order_id      on reviews(order_id);