create table if not exists otp_codes (
    id bigint generated by default as identity primary key,
    identifier varchar(255) not null,
    role varchar(50) not null,
    otp varchar(6) not null,
    expires_at timestamp not null,
    created_at timestamp not null
);

create index if not exists idx_otp_codes_identifier_role on otp_codes(identifier, role);
